---
# tasks file for kostyrevaa.foreman

- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_os_family }}.yml"
   - default.yml
  tags:
    - foreman
    - foreman-packages

- include: install.yml
  when: ansible_os_family == "RedHat"

- include: configure.yml
  when: foreman_setup_only_repo == false

- include: plugins.yml
  when: foreman_plugins is defined
  tags:
    - foreman-plugins
