---

- name: create apache override dir
  file: path=/etc/httpd/conf.d/05-foreman.d state=directory mode=0755

- name: create /var/run/rubygem-passenger
  file: path=/var/run/rubygem-passenger state=directory mode=0755
  when: ansible_distribution_major_version == '7'

- name: render apache vhost template
  template: src=../../templates/apache.vhost.j2 dest=/etc/httpd/conf.d/05-foreman.conf
  notify: restart apache
